variable "enable_ingress" {
  type        = bool
  description = "Enable ingress-nginx."
  default     = true
}

variable "enable_metrics" {
  type        = bool
  description = "Enable metrics-server."
  default     = true
}

variable "enable_argocd" {
  type        = bool
  description = "Enable Argo CD."
  default     = false
}

variable "kubeconfig_path" {
  type        = string
  description = "Path to kubeconfig generated by cluster module."
}
